name: CI — Test on PR & Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  # Fast checks — ONLY on push to dev
  fast-lint-and-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Compile requirements
        run: |
          pip-compile --extra dev pyproject.toml --output-file=requirements.txt

      - name: Install fast dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black mypy pytest

      - name: Run flake8
        run: flake8 src

      - name: Run black check
        run: black --check src

      - name: Run mypy
        run: mypy --ignore-missing-imports src

      - name: Run unit tests
        run: pytest -q tests/unit
